title: Stuart's PGCert Portfolio
description: Reflections and artefacts from my PGCert in Higher Education
baseurl: "/PGCert" # the subpath of your site
url: "https://stueyG1t.github.io" # the full base URL of your site

exclude:
  - README-OLD.md
  - example/
  - docs/
  - .gitignore
  - .DS_Store
remote_theme: mmistakes/so-simple-theme

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

skin: "/assets/css/skins/default.css"
locale: en-EN
date_format: "%B %-d, %Y"

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Optional features
mathjax:
  enable: false

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Front Matter Defaults
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Author
author:
  name: "Stuart Smith"
  picture:
  email:
  twitter:
  links:
    - title:
      url:
      icon:

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
